version: '3.0'
services:
  registry:
    container_name: docker-registry
    restart: always
    image: registry:2
    ports:
    - "5000:5000"
      #environment:
      #REGISTRY_AUTH: htpasswd
      #REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      #REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
    volumes:
            #  - ./auth:/auth
      - docker-registry-data:/var/lib/registry
volumes:
  docker-registry-data: {}
