---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcr-app-client-deploy
  namespace: tcr-ns
spec:
  selector:
    matchLabels:
      app: tcr-app-client
  replicas: 1
  template:
    metadata:
      name : tcr-app-client-pod
      labels:
        app: tcr-app-client
    spec:
      restartPolicy: Always
     #imagePullSecrets:
     #  - name: regcred
      containers:
        - name: tcr-app-client
          image: alaatriaa/frontend:env
          #resources:
                  #limits:
                  #memory: 1000Mi
                  #requests:
                  #memory: 700Mi
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
          
          livenessProbe:
            exec:
              command:
                - echo
                - "frontend svc!!"
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          
          env:

            - name: REACT_APP_BASE_URL_REGISTRY
              value: "http://10.0.0.10:5000"

            - name: REACT_APP_BASE_URL_REG
              value: "10.0.0.10:5000"

            - name: REACT_APP_BASE_URL_BACKEND
              value: "http://10.0.0.11:31001"

            - name : REACT_APP_REG_ID
              value : "123"
---
apiVersion: v1
kind: Service

metadata:
  name: tcr-app-client-svc
  namespace: tcr-ns
spec:
  selector:
    app: tcr-app-client
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      #nodePort: 31000
  type: ClusterIP 
